// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eobvvdaujhdrlkuogbid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvYnZ2ZGF1amhkcmxrdW9nYmlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMzQyNTksImV4cCI6MjA2NjcxMDI1OX0.PpdMDfsshy6lTzatTloApVLV8yC8PvZPrZj_LQUxvVc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);